# Generated by Django 3.1.7 on 2022-08-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_auto_20220829_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
